version: '3'

services:
  basex:
    image: basex/basexhttp:latest
    volumes:
      - ./res:/res
      - ./basexdata:/srv/BaseXData
  db:
    image: postgres
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/notenrollen_server
      - ./res:/res
    ports:
      - "8000:8000"
    depends_on:
      - db
