PREFIX  dbo: <http://dbpedia.org/ontology/>
PREFIX  dbp: <http://dbpedia.org/property/>
PREFIX dbr:  <http://dbpedia.org/resource/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

#convert to string explicitly to retrieve plain text
SELECT 
(str(?name_pre) AS ?name) 
(str(?gender_pre) AS ?gender) 
(str(?birth_pre) AS ?birth) 
(str(?death_pre) AS ?death) 
(str(?birthplace_pre) AS ?birthplace) 
(str(?deathplace_pre) AS ?deathplace) 
(str(?description_pre) AS ?description) 
(str(?thumbnail_pre) AS ?thumbnail) 
WHERE {
  ?person a dbo:Person ;
          foaf:name ?name_pre;
          foaf:gender ?gender_pre;
          dbo:birthDate ?birth_pre;
          dbo:deathDate ?death_pre;
          dbo:birthPlace ?birthplace_property;
          dbo:deathPlace ?deathplace_property;
          rdfs:comment ?description_pre;
	  #dct:description ?description_pre;
          dbo:thumbnail ?thumbnail_pre.
          ?deathplace_property rdfs:label ?deathplace_pre.		#get deathplace label 
          ?birthplace_property rdfs:label ?birthplace_pre.		#get birthplace label
  ?composition dbo:musicComposer ?person 		                #person who is a musical composer     
  FILTER ( lang(?name_pre) = 'en' and lang(?gender_pre) = 'en' and lang(?birthplace_pre) = 'en' and lang(?deathplace_pre) = 'en' and lang(?description_pre) = 'en')
  FILTER (regex(?name_pre, "SEARCH_TERM"))    #search by artist name, SEARCH_TERM will be replaced in corresponding function 
}
LIMIT 1
